install.packages('tableone')
install.packages('Matching')
install.packages('MatchIt')
library(tableone)
library(Matching)
library(MatchIt)
data(lalonde)
str(lalonde)
print('names lalonde:')
print(names(lalonde))
print('--------------')
